### ISSUE TITLE
Application won't run on Windows PC. 

### ISSUE THREAD

**Issue by paulossm** [ATID-PROJECT/atid-react#2]
after **npm start**, browser opens but the application shows the following error:
![image](https://user-images.githubusercontent.com/8640991/49671559-7a899f00-fa4f-11e8-9fb5-ed9a3c137e32.png)

**Comment by Mateus-Brito** [comment]
Hello, can you check if you have the most up-to-date version of the application? I could not reproduce the same error.

**Comment by paulossm** [comment]
After getting the updated version on branch master with git pull I still see the error.
One solution was to comment the line at:

72 `const ps = new PerfectScrollbar(this.refs.mainPanel);`
Dashboard.jsx

Now it works, even though there are a lot of error in the console.

**Comment by Mateus-Brito** [comment]
problem solved! You can look for a more recent version or visit the site: umurl.com
